
name: ico3_logger

version: 1.0.0

license: BSD-3-Clause

description: "Zero-setup, ultra-fast logs, live filtering, log sniffer, post-mortem, multi-loggers, JSON/CSV."
homepage: "https://github.com/ICOCUBE-Projects/Ico3_logger_dart"
repository: "https://github.com/ICOCUBE-Projects/Ico3_logger_dart"
issue_tracker: "https://github.com/ICOCUBE-Projects/Ico3_logger_dart/issues"
documentation: "https://github.com/ICOCUBE-Projects/ico3_logger_dart/blob/master/documentation/README.md"
topics:
  - debugging
  - logging

environment:
  sdk:  ">=3.6.0 <4.0.0"

executables:
  logViewer: cliViewer

# Add regular dependencies here.
dependencies:
  path: ^1.9.1
  intl:  '>=0.18.0 <=0.20.2'
  yaml: ^3.1.3
  web: ^1.1.1

dev_dependencies:
  lints: ^5.1.1
  test: ^1.25.15

  #flutter: any

platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows: