
name: ico3_logger

version: 1.0.0

license: BSD-3-Clause

description: "description: Zero-setup, ultra-fast logs ðŸš€: live filtering, post-mortem, multi-loggers, JSON/CSV."
homepage: "https://github.com/ICOCUBE-Projects/Ico3_logger_dart/tree/master"
repository: "https://github.com/ICOCUBE-Projects/Ico3_logger_dart/tree/master"
issue_tracker: "https://github.com/ICOCUBE-Projects/Ico3_logger_dart/issues"
topics:
  - debugging
  - logging

environment:
  sdk: ^3.6.1

# Add regular dependencies here.
dependencies:
  path: ^1.9.1
  intl: ^0.20.2
  yaml: ^3.1.3

dev_dependencies:
  lints: ^5.1.1
  test: ^1.25.15

platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows: